/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Chick({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/chick.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface3.geometry}
        material={nodes.chick_v2_7_3polySurface3.material}
        skeleton={nodes.chick_v2_7_3polySurface3.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface5.geometry}
        material={materials['chick_v2_7_3:lambert6']}
        skeleton={nodes.chick_v2_7_3polySurface5.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface7.geometry}
        material={nodes.chick_v2_7_3polySurface7.material}
        skeleton={nodes.chick_v2_7_3polySurface7.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface13.geometry}
        material={nodes.chick_v2_7_3polySurface13.material}
        skeleton={nodes.chick_v2_7_3polySurface13.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface14.geometry}
        material={nodes.chick_v2_7_3polySurface14.material}
        skeleton={nodes.chick_v2_7_3polySurface14.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface15.geometry}
        material={nodes.chick_v2_7_3polySurface15.material}
        skeleton={nodes.chick_v2_7_3polySurface15.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface6.geometry}
        material={nodes.chick_v2_7_3polySurface6.material}
        skeleton={nodes.chick_v2_7_3polySurface6.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface22.geometry}
        material={nodes.chick_v2_7_3polySurface22.material}
        skeleton={nodes.chick_v2_7_3polySurface22.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface2_1.geometry}
        material={nodes.chick_v2_7_3polySurface2_1.material}
        skeleton={nodes.chick_v2_7_3polySurface2_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface2_2.geometry}
        material={nodes.chick_v2_7_3polySurface2_2.material}
        skeleton={nodes.chick_v2_7_3polySurface2_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface1_1.geometry}
        material={nodes.chick_v2_7_3polySurface1_1.material}
        skeleton={nodes.chick_v2_7_3polySurface1_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface1_2.geometry}
        material={nodes.chick_v2_7_3polySurface1_2.material}
        skeleton={nodes.chick_v2_7_3polySurface1_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface21_1.geometry}
        material={nodes.chick_v2_7_3polySurface21_1.material}
        skeleton={nodes.chick_v2_7_3polySurface21_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface21_2.geometry}
        material={nodes.chick_v2_7_3polySurface21_2.material}
        skeleton={nodes.chick_v2_7_3polySurface21_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface20_1.geometry}
        material={nodes.chick_v2_7_3polySurface20_1.material}
        skeleton={nodes.chick_v2_7_3polySurface20_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface20_2.geometry}
        material={nodes.chick_v2_7_3polySurface20_2.material}
        skeleton={nodes.chick_v2_7_3polySurface20_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.chick_v2_7_3polySurface10.geometry}
        material={materials['chick_v2_7_3:lambert2']}
        skeleton={nodes.chick_v2_7_3polySurface10.skeleton}
      />
      <primitive object={nodes.chick_v2_7_3root} />
      <mesh geometry={nodes.pCylinder1.geometry} material={materials.lambert2} />
    </group>
  )
}

useGLTF.preload('/models/chick.glb')
